In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('EcoPreprocessed.csv')

In [3]:
data.head()

Unnamed: 0                                             review  polarity  \
0        3870                            able play youtube alexa    0.5000   
1          62  able recognize indian accent really well drop ...    0.2794   
2         487  absolute smart device amazon connect external ...    0.1827   
3        3204  absolutely amaze new member family control hom...    0.3682   
4        1265  absolutely amaze previously sceptical invest m...    0.2333   

   division  
0  positive  
1  positive  
2  positive  
3  positive  
4  positive

In [4]:
del data['Unnamed: 0']

In [5]:
data.head()

review  polarity  division
0                            able play youtube alexa    0.5000  positive
1  able recognize indian accent really well drop ...    0.2794  positive
2  absolute smart device amazon connect external ...    0.1827  positive
3  absolutely amaze new member family control hom...    0.3682  positive
4  absolutely amaze previously sceptical invest m...    0.2333  positive

In [6]:
del data['polarity']

In [7]:
data

review  division
0                               able play youtube alexa  positive
1     able recognize indian accent really well drop ...  positive
2     absolute smart device amazon connect external ...  positive
3     absolutely amaze new member family control hom...  positive
4     absolutely amaze previously sceptical invest m...  positive
...                                                 ...       ...
4079  yo yo yo love go if want one smart speaker val...  positive
4080                                      youtube music   neutral
4081  youtube support nahi kartasong recognise achha...   neutral
4082  yup proscontrols wipro light amazinglysony bra...   neutral
4083  zero integration capabilities fire tv devices ...  negative

[4084 rows x 2 columns]

In [8]:
from nltk.corpus import stopwords
import re
stp_word = stopwords.words('english')
        

In [9]:
data['review'] = data['review'].apply(lambda x:x.lower())

In [10]:
data['review'] = data['review'].apply(lambda x:re.sub('azAZ','',x))

In [11]:
data['review']= data['review'].apply(lambda x:' '.join([word for word in x.split() if word not in (stp_word)]))

In [12]:
data['review']

0                                 able play youtube alexa
1       able recognize indian accent really well drop ...
2       absolute smart device amazon connect external ...
3       absolutely amaze new member family control hom...
4       absolutely amaze previously sceptical invest m...
                              ...                        
4079    yo yo yo love go want one smart speaker value ...
4080                                        youtube music
4081    youtube support nahi kartasong recognise achha...
4082    yup proscontrols wipro light amazinglysony bra...
4083    zero integration capabilities fire tv devices ...
Name: review, Length: 4084, dtype: object

In [13]:
data['division'].value_counts()

positive    3066
neutral      536
negative     482
Name: division, dtype: int64

In [14]:
data['division'].replace({'positive':1,'neutral':0,'negative':-1})

0       1
1       1
2       1
3       1
4       1
       ..
4079    1
4080    0
4081    0
4082    0
4083   -1
Name: division, Length: 4084, dtype: int64

In [15]:
import nltk
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
lemmatizer = WordNetLemmatizer()

#Lemmatize String
def lemmatize_word(text):
    word_tokens = word_tokenize(text)
    #Providing context i.e. The part of speech
    lemmas = [lemmatizer.lemmatize(word, pos= 'v') for word in word_tokens]
    return lemmas

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [16]:
data['review'] = data['review'].apply(lemmatize_word)

In [17]:
data['review']

0                            [able, play, youtube, alexa]
1       [able, recognize, indian, accent, really, well...
2       [absolute, smart, device, amazon, connect, ext...
3       [absolutely, amaze, new, member, family, contr...
4       [absolutely, amaze, previously, sceptical, inv...
                              ...                        
4079    [yo, yo, yo, love, go, want, one, smart, speak...
4080                                     [youtube, music]
4081    [youtube, support, nahi, kartasong, recognise,...
4082    [yup, proscontrols, wipro, light, amazinglyson...
4083    [zero, integration, capabilities, fire, tv, de...
Name: review, Length: 4084, dtype: object

In [18]:
data.head()

review  division
0                       [able, play, youtube, alexa]  positive
1  [able, recognize, indian, accent, really, well...  positive
2  [absolute, smart, device, amazon, connect, ext...  positive
3  [absolutely, amaze, new, member, family, contr...  positive
4  [absolutely, amaze, previously, sceptical, inv...  positive

In [19]:
data['review'] = data['review'].apply(lambda x: ' '.join(x))

In [20]:
data['review']

0                                 able play youtube alexa
1       able recognize indian accent really well drop ...
2       absolute smart device amazon connect external ...
3       absolutely amaze new member family control hom...
4       absolutely amaze previously sceptical invest m...
                              ...                        
4079    yo yo yo love go want one smart speaker value ...
4080                                        youtube music
4081    youtube support nahi kartasong recognise achha...
4082    yup proscontrols wipro light amazinglysony bra...
4083    zero integration capabilities fire tv devices ...
Name: review, Length: 4084, dtype: object

In [21]:
data.head()

review  division
0                            able play youtube alexa  positive
1  able recognize indian accent really well drop ...  positive
2  absolute smart device amazon connect external ...  positive
3  absolutely amaze new member family control hom...  positive
4  absolutely amaze previously sceptical invest m...  positive

In [22]:
data['division']=data['division'].replace({'positive':1,'neutral':2,'negative':0})

In [23]:
data.head()

review  division
0                            able play youtube alexa         1
1  able recognize indian accent really well drop ...         1
2  absolute smart device amazon connect external ...         1
3  absolutely amaze new member family control hom...         1
4  absolutely amaze previously sceptical invest m...         1

In [24]:
label = data['division']

In [25]:
data = data.drop('division',axis=1)

In [26]:
data

review
0                               able play youtube alexa
1     able recognize indian accent really well drop ...
2     absolute smart device amazon connect external ...
3     absolutely amaze new member family control hom...
4     absolutely amaze previously sceptical invest m...
...                                                 ...
4079  yo yo yo love go want one smart speaker value ...
4080                                      youtube music
4081  youtube support nahi kartasong recognise achha...
4082  yup proscontrols wipro light amazinglysony bra...
4083  zero integration capabilities fire tv devices ...

[4084 rows x 1 columns]

## Performing Train-Test Split

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(data['review'],label,test_size=0.2,random_state=42)

In [28]:
Y_train.value_counts()

1    2469
2     409
0     389
Name: division, dtype: int64

In [29]:
X_train.shape

(3267,)

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()


In [31]:
Y_train.shape

(3267,)

In [32]:
X_test.shape

(817,)

In [33]:
data.shape

(4084, 1)

In [34]:
X_train_tfidf = tfid.fit_transform(X_train)

In [35]:
X_test_tfid = tfid.transform(X_test)

In [36]:
print(X_train_tfidf)

  (0, 1296)	0.6928461823929611
  (0, 2868)	0.6117816272655955
  (0, 186)	0.3816901990931382
  (1, 2253)	1.0
  (2, 2528)	0.647358579607781
  (2, 2613)	0.5403712753015455
  (2, 2253)	0.5375181431702353
  (3, 3962)	0.21946471760604835
  (3, 1014)	0.38344090359772404
  (3, 2775)	0.39684377478628324
  (3, 2617)	0.42921800486310074
  (3, 3098)	0.17440569451273202
  (3, 1632)	0.13395583049505685
  (3, 3555)	0.48011001592158187
  (3, 3050)	0.42921800486310074
  (4, 927)	0.5227149464368135
  (4, 3537)	0.4571057073006847
  (4, 488)	0.40747423385679893
  (4, 1055)	0.26162721302708
  (4, 879)	0.3738205261051559
  (4, 128)	0.19108617404013853
  (4, 4260)	0.3272364521632086
  (5, 1632)	1.0
  (6, 2586)	0.11899575465058125
  (6, 3813)	0.2005265298566465
  :	:
  (3264, 503)	0.169109696883353
  (3264, 2967)	0.19248895759744247
  (3264, 1797)	0.17912358048542545
  (3264, 324)	0.20998255565416482
  (3264, 2275)	0.21056670807279998
  (3264, 1055)	0.1611454282834255
  (3264, 128)	0.11769671433816821
  (3265

In [37]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_tfidf.toarray(),Y_train)

GaussianNB()

In [38]:
pred = gnb.predict(X_test_tfid.toarray())

In [39]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [40]:
accuray_score_naive_bayes = accuracy_score(pred,Y_test)

In [41]:
accuray_score_naive_bayes

0.5042839657282742

In [42]:
confusion_matrix_naive_bayes = confusion_matrix(pred,Y_test)

In [43]:
confusion_matrix

<function sklearn.metrics._classification.confusion_matrix(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)>

In [44]:
print(confusion_matrix_naive_bayes)

[[ 36 184  23]
 [ 42 301  29]
 [ 15 112  75]]


## using XGB-Classifier

In [45]:
from xgboost import XGBClassifier

In [48]:
xgb = XGBClassifier(objective='multi:softmax')
xgb.fit(X_train_tfidf,Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softmax',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [49]:
pred_xbg = xgb.predict(X_test_tfid)

In [51]:
pred_acc_xgb = accuracy_score(pred_xbg,Y_test)

In [52]:
print(pred_acc_xgb)

0.8849449204406364


In [53]:
confusion_matrix_for_xgb = confusion_matrix(pred_xbg,Y_test)

In [54]:
print(confusion_matrix_for_xgb)

[[ 52  13   3]
 [ 29 567  20]
 [ 12  17 104]]


In [55]:
classification_report_for_xgb = classification_report(pred_xbg,Y_test)

In [56]:
print(classification_report_for_xgb)

              precision    recall  f1-score   support

           0       0.56      0.76      0.65        68
           1       0.95      0.92      0.93       616
           2       0.82      0.78      0.80       133

    accuracy                           0.88       817
   macro avg       0.78      0.82      0.79       817
weighted avg       0.90      0.88      0.89       817



In [71]:
#Using Logistic_Regression
from sklearn.linear_model import LogisticRegression


In [72]:
lg = LogisticRegression(max_iter=1000,solver='saga')
lg.fit(X_train_tfidf,Y_train)

LogisticRegression(max_iter=1000, solver='saga')

In [73]:
pred_lg = lg.predict(X_test_tfid)

In [74]:
accuracy_score_using_lg = accuracy_score(pred_lg,Y_test)

In [75]:
print(accuracy_score_using_lg)

0.795593635250918


In [76]:
print(X_train_tfidf)

  (0, 1296)	0.6928461823929611
  (0, 2868)	0.6117816272655955
  (0, 186)	0.3816901990931382
  (1, 2253)	1.0
  (2, 2528)	0.647358579607781
  (2, 2613)	0.5403712753015455
  (2, 2253)	0.5375181431702353
  (3, 3962)	0.21946471760604835
  (3, 1014)	0.38344090359772404
  (3, 2775)	0.39684377478628324
  (3, 2617)	0.42921800486310074
  (3, 3098)	0.17440569451273202
  (3, 1632)	0.13395583049505685
  (3, 3555)	0.48011001592158187
  (3, 3050)	0.42921800486310074
  (4, 927)	0.5227149464368135
  (4, 3537)	0.4571057073006847
  (4, 488)	0.40747423385679893
  (4, 1055)	0.26162721302708
  (4, 879)	0.3738205261051559
  (4, 128)	0.19108617404013853
  (4, 4260)	0.3272364521632086
  (5, 1632)	1.0
  (6, 2586)	0.11899575465058125
  (6, 3813)	0.2005265298566465
  :	:
  (3264, 503)	0.169109696883353
  (3264, 2967)	0.19248895759744247
  (3264, 1797)	0.17912358048542545
  (3264, 324)	0.20998255565416482
  (3264, 2275)	0.21056670807279998
  (3264, 1055)	0.1611454282834255
  (3264, 128)	0.11769671433816821
  (3265